// Country list with major cities per country.
// City dropdown is filtered by selected country.

export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Argentina', 'Australia', 'Austria',
  'Bangladesh', 'Belgium', 'Brazil', 'Cambodia', 'Canada', 'Chile', 'China',
  'Colombia', 'Czech Republic', 'Denmark', 'Egypt', 'Finland', 'France',
  'Germany', 'Ghana', 'Greece', 'Hong Kong', 'Hungary', 'India', 'Indonesia',
  'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Japan', 'Jordan', 'Kenya',
  'South Korea', 'Kuwait', 'Laos', 'Lebanon', 'Libya', 'Luxembourg',
  'Macau', 'Malaysia', 'Maldives', 'Mexico', 'Morocco', 'Myanmar',
  'Nepal', 'Netherlands', 'New Zealand', 'Nigeria', 'Norway', 'Oman',
  'Pakistan', 'Palestine', 'Philippines', 'Poland', 'Portugal', 'Qatar',
  'Romania', 'Russia', 'Saudi Arabia', 'Singapore', 'South Africa', 'Spain',
  'Sri Lanka', 'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey',
  'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States',
  'Vietnam', 'Yemen',
]

export const CITIES_BY_COUNTRY = {
  Malaysia: [
    'Alor Setar', 'Ampang', 'Batu Pahat', 'Butterworth', 'Ipoh', 'Johor Bahru',
    'Kajang', 'Klang', 'Kota Bharu', 'Kota Kinabalu', 'Kuala Lumpur', 'Kuala Terengganu',
    'Kuantan', 'Kuching', 'Miri', 'Petaling Jaya', 'Putrajaya', 'Sandakan',
    'Seremban', 'Shah Alam', 'Sibu', 'Subang Jaya', 'Taiping',
  ],
  Singapore: ['Singapore'],
  Indonesia: [
    'Bandung', 'Bekasi', 'Denpasar', 'Jakarta', 'Makassar', 'Medan',
    'Palembang', 'Semarang', 'Surabaya', 'Yogyakarta',
  ],
  Thailand: [
    'Bangkok', 'Chiang Mai', 'Chiang Rai', 'Hat Yai', 'Khon Kaen',
    'Nakhon Ratchasima', 'Pattaya', 'Phuket', 'Udon Thani',
  ],
  Philippines: [
    'Cebu City', 'Davao City', 'Makati', 'Manila', 'Quezon City',
    'Taguig', 'Zamboanga City',
  ],
  Vietnam: [
    'Can Tho', 'Da Nang', 'Hai Phong', 'Hanoi', 'Ho Chi Minh City',
    'Hue', 'Nha Trang',
  ],
  Myanmar: ['Mandalay', 'Naypyidaw', 'Yangon'],
  Cambodia: ['Phnom Penh', 'Siem Reap', 'Sihanoukville'],
  Laos: ['Luang Prabang', 'Vientiane'],
  China: [
    'Beijing', 'Chengdu', 'Chongqing', 'Guangzhou', 'Hangzhou', 'Nanjing',
    'Shanghai', 'Shenzhen', 'Wuhan', 'Xi\'an',
  ],
  'Hong Kong': ['Hong Kong', 'Kowloon', 'New Territories'],
  Macau: ['Macau'],
  Taiwan: ['Kaohsiung', 'New Taipei', 'Taichung', 'Tainan', 'Taipei'],
  Japan: [
    'Fukuoka', 'Hiroshima', 'Kyoto', 'Nagoya', 'Osaka', 'Sapporo',
    'Sendai', 'Tokyo', 'Yokohama',
  ],
  'South Korea': ['Busan', 'Daegu', 'Daejeon', 'Gwangju', 'Incheon', 'Seoul', 'Ulsan'],
  India: [
    'Ahmedabad', 'Bangalore', 'Chennai', 'Delhi', 'Hyderabad', 'Jaipur',
    'Kolkata', 'Mumbai', 'Pune', 'Surat',
  ],
  Bangladesh: ['Chattogram', 'Dhaka', 'Khulna', 'Rajshahi', 'Sylhet'],
  Pakistan: ['Faisalabad', 'Islamabad', 'Karachi', 'Lahore', 'Rawalpindi'],
  'Sri Lanka': ['Colombo', 'Kandy', 'Negombo'],
  Nepal: ['Kathmandu', 'Lalitpur', 'Pokhara'],
  'Saudi Arabia': ['Dammam', 'Jeddah', 'Mecca', 'Medina', 'Riyadh'],
  'United Arab Emirates': ['Abu Dhabi', 'Ajman', 'Dubai', 'Sharjah'],
  Qatar: ['Al Rayyan', 'Doha'],
  Kuwait: ['Kuwait City', 'Salmiya'],
  Oman: ['Muscat', 'Salalah', 'Sohar'],
  Jordan: ['Amman', 'Aqaba', 'Irbid', 'Zarqa'],
  Lebanon: ['Beirut', 'Sidon', 'Tripoli'],
  Israel: ['Haifa', 'Jerusalem', 'Tel Aviv'],
  Iraq: ['Baghdad', 'Basra', 'Erbil', 'Mosul'],
  Iran: ['Isfahan', 'Mashhad', 'Shiraz', 'Tabriz', 'Tehran'],
  Turkey: [
    'Adana', 'Ankara', 'Antalya', 'Bursa', 'Gaziantep',
    'Istanbul', 'Izmir', 'Konya',
  ],
  Egypt: ['Alexandria', 'Cairo', 'Giza', 'Luxor', 'Port Said'],
  Morocco: ['Casablanca', 'Fes', 'Marrakech', 'Rabat', 'Tangier'],
  Libya: ['Benghazi', 'Tripoli'],
  Algeria: ['Algiers', 'Constantine', 'Oran'],
  Nigeria: ['Abuja', 'Enugu', 'Ibadan', 'Kano', 'Lagos', 'Port Harcourt'],
  Ghana: ['Accra', 'Kumasi', 'Tamale'],
  Kenya: ['Kisumu', 'Mombasa', 'Nairobi'],
  'South Africa': ['Cape Town', 'Durban', 'Johannesburg', 'Pretoria'],
  Australia: [
    'Adelaide', 'Brisbane', 'Canberra', 'Darwin', 'Gold Coast',
    'Melbourne', 'Perth', 'Sydney',
  ],
  'New Zealand': ['Auckland', 'Christchurch', 'Dunedin', 'Wellington'],
  'United Kingdom': [
    'Birmingham', 'Bristol', 'Edinburgh', 'Glasgow', 'Leeds',
    'Liverpool', 'London', 'Manchester', 'Newcastle',
  ],
  Ireland: ['Cork', 'Dublin', 'Galway', 'Limerick'],
  France: [
    'Bordeaux', 'Lille', 'Lyon', 'Marseille', 'Nantes', 'Nice', 'Paris', 'Toulouse',
  ],
  Germany: [
    'Berlin', 'Cologne', 'Dresden', 'Düsseldorf', 'Frankfurt',
    'Hamburg', 'Leipzig', 'Munich', 'Stuttgart',
  ],
  Netherlands: ['Amsterdam', 'Eindhoven', 'Rotterdam', 'The Hague', 'Utrecht'],
  Belgium: ['Antwerp', 'Brussels', 'Ghent', 'Liège'],
  Luxembourg: ['Luxembourg City'],
  Switzerland: ['Basel', 'Bern', 'Geneva', 'Lausanne', 'Zurich'],
  Austria: ['Graz', 'Innsbruck', 'Linz', 'Salzburg', 'Vienna'],
  Spain: ['Barcelona', 'Bilbao', 'Madrid', 'Seville', 'Valencia', 'Zaragoza'],
  Portugal: ['Braga', 'Coimbra', 'Lisbon', 'Porto'],
  Italy: ['Bologna', 'Florence', 'Genoa', 'Milan', 'Naples', 'Palermo', 'Rome', 'Turin', 'Venice'],
  Greece: ['Athens', 'Heraklion', 'Thessaloniki'],
  Poland: ['Gdańsk', 'Kraków', 'Łódź', 'Poznań', 'Warsaw', 'Wrocław'],
  'Czech Republic': ['Brno', 'Ostrava', 'Prague'],
  Romania: ['Bucharest', 'Cluj-Napoca', 'Timișoara'],
  Hungary: ['Budapest', 'Debrecen', 'Miskolc'],
  Denmark: ['Aarhus', 'Copenhagen', 'Odense'],
  Sweden: ['Gothenburg', 'Malmö', 'Stockholm', 'Uppsala'],
  Norway: ['Bergen', 'Oslo', 'Trondheim'],
  Finland: ['Espoo', 'Helsinki', 'Tampere', 'Turku'],
  Russia: [
    'Ekaterinburg', 'Kazan', 'Moscow', 'Nizhny Novgorod',
    'Novosibirsk', 'Omsk', 'Rostov-on-Don', 'Saint Petersburg', 'Samara',
  ],
  Ukraine: ['Dnipro', 'Kharkiv', 'Kyiv', 'Lviv', 'Odesa'],
  'United States': [
    'Atlanta', 'Austin', 'Boston', 'Chicago', 'Dallas', 'Denver',
    'Houston', 'Las Vegas', 'Los Angeles', 'Miami', 'Minneapolis',
    'New York', 'Philadelphia', 'Phoenix', 'Portland', 'San Diego',
    'San Francisco', 'Seattle', 'Washington D.C.',
  ],
  Canada: [
    'Calgary', 'Edmonton', 'Montreal', 'Ottawa', 'Quebec City',
    'Toronto', 'Vancouver', 'Winnipeg',
  ],
  Mexico: [
    'Guadalajara', 'Mexico City', 'Monterrey', 'Puebla', 'Tijuana',
  ],
  Brazil: [
    'Belo Horizonte', 'Brasília', 'Curitiba', 'Fortaleza', 'Manaus',
    'Porto Alegre', 'Recife', 'Rio de Janeiro', 'Salvador', 'São Paulo',
  ],
  Argentina: ['Buenos Aires', 'Córdoba', 'Mendoza', 'Rosario'],
  Colombia: ['Barranquilla', 'Bogotá', 'Cali', 'Medellín'],
  Chile: ['Concepción', 'Santiago', 'Valparaíso'],
  'Maldives': ['Malé'],
  Palestine: ['Gaza', 'Ramallah'],
  Yemen: ["Aden", "Sana'a"],
  Afghanistan: ['Kabul', 'Kandahar', 'Mazar-i-Sharif'],
  Albania: ['Durrës', 'Tirana'],
}
